zuul:
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  sensitive-headers:
  prefix: /api
  routes:
    member:
      path: /member/**
      serviceId: member-soa
#      url: https://admin.eggxiaoer.net/api/member/
    trade:
      path: /trade/**
      serviceId: trade-soa
#      url: https://admin.eggxiaoer.net/api/trade/
    basic:
      path: /basic/**
      serviceId: basic-soa
#      url: https://admin.eggxiaoer.net/api/basic/

ribbon:
  read-timeout: 60000
  connect-timeout: 60000

logging:
  config: classpath:logback-spring.xml
  home: /tmp/logs/
  level:
    root: info
    com.netflix.discovery: off
#    org.springframework.cloud: info




